# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MLE_BL_cpp <- function(r, eps, Mx, Bk, M2E) {
    .Call(`_hofa_MLE_BL_cpp`, r, eps, Mx, Bk, M2E)
}

