#' Genereate panel data from Higher-order multi-cumulant Factor Model
#'
#' @param n An integer, the number of variables
#' @param t An integer, the number of observations
#' @param k An integer, the number of factors
#' @param par_f A kx3 vector, the parameters of factor distribution, par_f = c(eta_f1,eta_f2,...,p_f1,p_f2,...,q_f1,q_f2,...)
#' @param par_e A vector, the parameters of error distribution. par_e = c(theta,eta_e,p_e,q_e,beta,J,rho)
#' @param msig_e The maximum variance of error terms
#' @param rho_ar A kx1 vector, the auto-regressive parameters of factors
#' @param ... Any other passthru parameters
#' @return A T x N matrix, generated by Higher-order multi-cumulant Factor Model.
#' @examples
#' n = 20;t = 100;k = 2;msig_e = 7;
#' par_f = c(0.5,0,2,2,Inf,Inf);
#' par_e = c(1,0,2,Inf,0,0,0);
#' rho_ar = c(0.5,0.2);
#' SimHFA(n,t,k,par_f,par_e,rho_ar,msig_e)

SimHFA = function(n,t,k,par_f,par_e,rho_ar,msig_e,...){

  eta_f= par_f[1:k]
  df_f= par_f[(k+1):(2*k)]
  p_f = par_f[(2*k + 1):(3*k)]
  theta = par_e[1]
  eta_e = par_e[2]
  p_e  = par_e[3]
  q_e = par_e[4]
  beta = par_e[5]
  J = par_e[6]
  rho = par_e[7]

  var_f = rep(1,k)

  m = min(sqrt(t),n)

  W=matrix(rnorm(n*k),n,k)

  sig_e = runif(n,0.1,msig_e)

  FF = matrix(NA,t,k)
  for (ii in 1:k) {
    FF[,ii] <- arima.sim(list(ar = rho_ar[ii]),t,rand.gen = function(n,...){rsgt(n,0,1,eta_f[ii],p=p_f[ii],q=df_f[ii])})
  }


  if(rho != 0){
    p = n

    ut = matrix(NA,t,n)
    for (j in 1:n) {
      ut[,j] = rsgt(t,0,1,eta_e,p_e,q_e,var.adj = T)
    }

    aast = c(1:p)
    et = matrix(0,t,p)
    for (j in 1:p) {
      ast = aast[j]
      et[,ast] = arima.sim(list(order = c(1,0,0), ar = rho),n = t ,rand.gen = rccsgt , ast = ast , p = p,beta = beta ,ut =ut, J = J)
    }
    et = et[,-((n+1):(n+2))]
    theta = rep(1,t)%*%t(sig_e)
    E<-sqrt(theta)*et*sqrt((1-rho^2)/(1+2*J*beta^2))
  }

  if(rho == 0){
    p = n
    ut = matrix(NA,t,n)
    for (j in 1:n) {
      ut[,j] = rsgt(t,0,1,eta_e,p_e,q_e,var.adj = T)
    }

    aast = c(1:p)
    et = matrix(0,t,p)
    for (j in 1:p) {
      ast = aast[j]
      et[,ast] = rccsgt(ast = ast,p = p,beta = beta ,ut =ut, J = J)
    }
    theta = rep(1,t)%*%t(sig_e)
    E<-sqrt(theta)*et*sqrt((1-rho^2)/(1+2*J*beta^2))

  }

  X = FF%*%t(W)+E

  return(list(X = X,W = W,FF = FF,E = E))
}
